name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "https://github.com/EpitechPromo2028/B-DOP-200-BDX-2-1-chocolatine-faris.khsime"
  EXECUTABLES: "exec"

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Run Coding Style Checker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/epitech/coding-style-checker:latest check.sh
          $(pwd) $(pwd)

  Checking_program_compilation:
    name: Checking Program Compilation
    runs-on: epitechcontent/epitest-docker
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Compile with Make
        run: make
        timeout-minutes: 2

      - name: Clean repository
        run: make clean

      - name: Check Executables
        run: |
          IFS=',' read -ra EXECS <<< "${EXECUTABLES}"
          for EXEC in "${EXECS[@]}"; do
            if [ ! -x "./$EXEC" ]; then
              echo "Error: $EXEC not found or not executable"
              exit 1
            fi
          done

  run-tests:
    name: Run Tests
    runs-on: epitechcontent/epitest-docker
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Run Tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    name: Pushing to mirror repository
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout GH repo
        uses: actions/checkout@master

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
